---
title: "张聪莉个人主页"

output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
     body { background-color: #cfced6; }
     pre, pre:not([class]) { background-color: red; }
</style>
```{css, echo=FALSE}
p {
  font-size: 15px;
}

p.small {
  line-height: 0.8;
}

p.big {
  line-height: 1.0;
}
```

## 个人信息

张聪莉

教育学博士候选人

俄勒冈大学教育学院（US NEWS 2023 最佳教育学院排名第14）

地址：102J Lokey Education Bldg, 5267 University of Oregon, Eugene, OR 97403-5267

电子邮件：congliclairezhang@gmail.com 

电话：415-596-7343

## 我的简历

### 教育背景及专业：

教育量化研究方法，教育学博士，俄勒冈大学，美国，
组织领导学硕士，东北大学，美国
教育学学士（数学），河北师范大学，中国

### 专业领域与资格：
教育数据科学（R 语言），俄勒冈大学，美国
人力资源，东北大学，美国
中学教师资格证书，河北省石家庄市教育局，中国

### 工作经历

研究助理，俄勒冈大学，美国

协助由美国研究所资助的研究项目，学校改进网络(Gates NSI)持续改进计划的评估
参与一系列项目评估，包括编码手册的制定、文物编码、数据分析和报告撰写
• 主要研究员，石家庄市第22中学，中国，2011-2016
领导一个由23名成员组成的研究团队，实施和评估为期五年的学习为导向的家庭干预计划，该计划是中国青少年儿童研究中心全国重点研究项目“学校、家庭和社会联合教育框架研究”的子项目。
成就：2012年两次全国会议演讲；2016年杰出研究员奖；2016年杰出最终报告奖
教学经验：
• 讲师，俄勒冈大学，美国，2019-2022

研究生课程：量化研究方法系列课程的R工作坊和实验室会话，EDUC 641、643和645，教育与人类服务应用统计学I、II和III
本科课程：EDLD 211，探究领导力和EDLD 313，未来领袖的项目评估
• 课程构建者，俄勒冈大学，美国，2019-2022
研究生课程（助理）：EDUC 641、643和645，教育与人类服务应用统计学I、II和III

#### 我的科研

