---
title: "Congli (Claire) Zhang"

output: 
  html_document:
    css: "splendor.min.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
     body { background-color: #f2e6dc; }
     pre, pre:not([class]) { background-color: red; }
</style>
```{css, echo=FALSE}
p {
  font-size: 19px;
}
```
#### *About me*

Hello, welcome to my website. 

I am currently a doctoral candidate at the University of Oregon, majoring in Quantitative Research Methods in Education and specialized in Educational Data Science. My best programming language is R. 
I am on track to graduate in June, 2023 and am currently on job market looking for academic positions in universities as well as applied analyst jobs in educational research organizations. Feel free to learn more about my qualifications and achievements in my CV down below and contact me at congliclairezhang@gmail.com with potential job opportunities.

I obtained systematic training in quantitative research methods and educational data science in my doctoral program. My research competencies include experimental and quasi-experimental research design, generalized linear models, multilevel models, structural equation modeling, advanced measurement and assessment methods, implementation science, policy analysis, program evaluation, meta-analysis, scholarly writing, and grant writing. Beyond my program, I took courses from the Economics department to add causal inference methods to my toolkit. I also finished a sequence of four R courses and obtained a specialization in educational data science. 

I am passionate about education systems change and am aspired to be an applied researcher who bridges the gaps between scientific research and educational policy and practice. I kept honing my research skills by applying my expertise to a variety of research projects. Both independently and in collaboration with my co-authors, I led several research projects and presented my papers in multiple national conferences such as AERA, AEFP, and SREE. 

My current research scholarship centers on the causal impacts of various school-, teacher-, family-level factors on student performance as well as non-academic outcomes in P-12 education. My dissertation consists of three separate articles investigating the causal impacts of teacher human capital characteristics, advisor-advisee relationships, and classroom teacher-student relationships on student performance and attitude. Another ongoing study is focusing on gender gaps and causal evidence on teacher factors that bridge these gaps. 

#### *My CV*

Learn more about me via my [vita](./docs/Zhang_CV.pdf).

#### *My research*

Most recent research paper (2nd chapter of my dissertation): [*Whether Having Advisor-Advisee Relationship with Content Teachers Improve Student Academic Outcomes? Causal Evidence from Chinese Junior High Schools.*](./docs/Zhang_writing.pdf)

Most recent conference paper presentations (AEFP 2023, Denver): 1. [*Education, Experience, or More? Causal Impacts of Teacher Human Capital on Student Learning in Chinese Junior High Schools*](./1_presentation/AEFP2023-char/char.html), and 2. *Investigating the Causal Impact of Teacher Gender Matching on Student Learning*.

My dissertation proposal: *Teacher Characteristics, Teacher-Student Relationship, and Student Academic Outcomes in Chinese Junior High Schools.*
